# Generated by Django 2.2.10 on 2020-05-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='FruitEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='水果名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('source', models.CharField(max_length=30, verbose_name='源产地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Category')),
                ('users', models.ManyToManyField(db_table='t_collect', related_name='fruits', to='demo.UserEntity', verbose_name='收藏用户列表')),
            ],
            options={
                'verbose_name': '水果表',
                'verbose_name_plural': '水果表',
                'db_table': 't_fruit',
            },
        ),
    ]
